version: '3.3'

volumes:
  pg_data:
  static:
  media:


services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: shdar/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: shdar/foodgram_frontend
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: shdar/foodgram_nginx
    env_file: .env
    ports:
      - 7000:80
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/app/media/
    depends_on:
      - backend
